services:
  viio-frontend:
    build: ./viio-frontend
    ports:
      - 3000:3000
    volumes:
      - ./viio-frontend:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      - NODE_ENV=development